In [6]:
# %pip install pandas numpy matplotlib seaborn scipy scikit-learn tensorflow
%pip install bs4 statsmodels

  Using cached statsmodels-0.14.4-cp311-cp311-win_amd64.whl.metadata (9.5 kB)
  Using cached patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Using cached statsmodels-0.14.4-cp311-cp311-win_amd64.whl (9.9 MB)
Using cached patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Note: you may need to restart the kernel to use updated packages.


In [7]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from urllib.request import urlopen 
from bs4 import BeautifulSoup 
import time

from matplotlib import font_manager, rc

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows인 경우
# plt.rcParams['font.family'] = 'AppleGothic'  # MacOS인 경우

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

import statsmodels.api as sm
from statsmodels.formula.api import ols

import warnings
warnings.filterwarnings("ignore")

import math 
from scipy.stats import logistic
from scipy.stats import trim_mean
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale 

from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, mean_squared_error

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import *

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn import tree

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.svm import SVC, SVR
from sklearn.cluster import KMeans

from tensorflow.keras.layers import Dense, Flatten, Dropout, Activation
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from tensorflow.keras.optimizers import Adam


In [8]:
# 5 Python 실습
# • 1,2,10 세 장의 카드가 있는 상자가 있다. 무작위 복원추출로 카드를 1장
# 씩 뽑아 그 합을 확률변수 X로 정의하자.
# Q8) 복원추출 횟수=10번 하는 경우 경험적 히스토그램을 작성하세요.
# (the number of repetitions=50000)


# 코드작성

# 카드 번호 조합
card = [1,2,10]

#반복 횟수
repeatition = 5


# 반복 횟수만큼 반복
for i in range(repeatition):
  X = np.random.choice(card, size=1)
  print(X)


[ 2 10  1  1  1  1  1 10  1  2]
[10 10 10 10 10  2  2  2  1 10]
[2 1 2 1 2 1 2 2 2 2]
[10  1  1 10 10 10  2 10  2 10]
[ 1 10  1  1  2 10  1  2  1  1]
